baseURL: "https://uridickman.github.io" 
title: Uri Dickman
theme: PaperMod

#design:
  #background:
    #image:
      #filename: bg-hue.svg

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Dashboard
          weight: 1
          url: https://uridickman.github.io
        - name: Publications
          weight: 2
          url: publications
        - name: Code
          weight: 3
          url: code/
       
params:
    description: "This website hosts Uri Dickmnan's resume, contact information, publications, and codes."
    author: Uri Dickman
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark 
    hideFooter: false 
    disableThemeToggle: true 
    ShowShareButtons: false 
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["publications","code"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true 
          title: Uri Dickman
          subtitle: "I am a researcher at Case Western Reserve University in computational neuroscience. I'm an incoming PhD student in Mechanical Engineering at University of California-Santa Barbara. I am working towards a career in developing high-performance computing software with applications to additive manufacturing, solid mechanics, and materials science at a national laboratory."
          imageUrl: "profile.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: publications
            - name: Code
              url: code/

    socialIcons:
        - name: Resume
          url: resume.pdf
        - name: Email
          url: mailto:udickman@engineering.ucsb.edu
      # - name: Scholar
      #   url: 
        - name: ORCiD
          url: https://orcid.org/0009-0001-5136-7641
        - name: GitHub
          url: https://github.com/uridickman
        - name: LinkedIn
          url: https://www.linkedin.com/in/uri-dickman/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      #text: "Uri Dickman"
      #icon: favicon.ico
      #iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
