baseURL: "https://uridickman.github.io" 
title: Uri Dickman
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "I am a researcher at Case Western Reserve University in computational neuroscience. This fall, I will be starting my Ph.D. in Mechanical Engineering at the University of California - Santa Barbara."
    author: Uri Dickman
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    # MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Uri Dickman
          subtitle: "I am a researcher at Case Western Reserve University in computational neuroscience. This fall, I will be starting my Ph.D. in Mechanical Engineering at the University of California - Santa Barbara."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          # buttons:
          #   - name: Papers
          #     url: papers/
          #   - name: Courses
          #     url: courses/
          #   - name: Data
          #     url: data/
          #   - name: Books
          #     url: books/
          #   - name: Tags
          #     url: tags/
          #   - name: Archive
          #     url: archive/
          #   - name: Blog
          #     url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:uridickman@gmail.com
        - name: Zoom
          url: https://cwru.zoom.us/j/7139360613?pwd=ZKpWC2RXtCIXCxweTKDFRDQZXJ2aO7.1
        - name: Location
          url: location/
        - name: GitHub
          url: https://github.com/uridickman
        - name: LinkedIn
          url: https://www.linkedin.com/in/uri-dickman/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Uri Dickman"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2